/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ProductIdIndexRouteImport } from './routes/product.$id.index'
import { Route as ProductIdSpecificationsGateIdRouteImport } from './routes/product.$id.specifications.$gateId'

const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdIndexRoute = ProductIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductIdRoute,
} as any)
const ProductIdSpecificationsGateIdRoute =
  ProductIdSpecificationsGateIdRouteImport.update({
    id: '/specifications/$gateId',
    path: '/specifications/$gateId',
    getParentRoute: () => ProductIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/analytics': typeof AnalyticsRoute
  '/library': typeof LibraryRoute
  '/product/$id': typeof ProductIdRouteWithChildren
  '/product/$id/': typeof ProductIdIndexRoute
  '/product/$id/specifications/$gateId': typeof ProductIdSpecificationsGateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/analytics': typeof AnalyticsRoute
  '/library': typeof LibraryRoute
  '/product/$id': typeof ProductIdIndexRoute
  '/product/$id/specifications/$gateId': typeof ProductIdSpecificationsGateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/analytics': typeof AnalyticsRoute
  '/library': typeof LibraryRoute
  '/product/$id': typeof ProductIdRouteWithChildren
  '/product/$id/': typeof ProductIdIndexRoute
  '/product/$id/specifications/$gateId': typeof ProductIdSpecificationsGateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/analytics'
    | '/library'
    | '/product/$id'
    | '/product/$id/'
    | '/product/$id/specifications/$gateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/analytics'
    | '/library'
    | '/product/$id'
    | '/product/$id/specifications/$gateId'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/analytics'
    | '/library'
    | '/product/$id'
    | '/product/$id/'
    | '/product/$id/specifications/$gateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LibraryRoute: typeof LibraryRoute
  ProductIdRoute: typeof ProductIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id/': {
      id: '/product/$id/'
      path: '/'
      fullPath: '/product/$id/'
      preLoaderRoute: typeof ProductIdIndexRouteImport
      parentRoute: typeof ProductIdRoute
    }
    '/product/$id/specifications/$gateId': {
      id: '/product/$id/specifications/$gateId'
      path: '/specifications/$gateId'
      fullPath: '/product/$id/specifications/$gateId'
      preLoaderRoute: typeof ProductIdSpecificationsGateIdRouteImport
      parentRoute: typeof ProductIdRoute
    }
  }
}

interface ProductIdRouteChildren {
  ProductIdIndexRoute: typeof ProductIdIndexRoute
  ProductIdSpecificationsGateIdRoute: typeof ProductIdSpecificationsGateIdRoute
}

const ProductIdRouteChildren: ProductIdRouteChildren = {
  ProductIdIndexRoute: ProductIdIndexRoute,
  ProductIdSpecificationsGateIdRoute: ProductIdSpecificationsGateIdRoute,
}

const ProductIdRouteWithChildren = ProductIdRoute._addFileChildren(
  ProductIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AnalyticsRoute: AnalyticsRoute,
  LibraryRoute: LibraryRoute,
  ProductIdRoute: ProductIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
